### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by dblock** [dblock/ruby-enum#15]
Lets do a release after #14 is merged. Maybe 0.7.0 since #3 is a pretty big piece of functionality. 

@laertispappas care to follow https://github.com/dblock/ruby-enum/blob/master/RELEASING.md then?

**Comment by laertispappas** [comment]
@dblock  Sure let me handle it. Thanks

**Comment by laertispappas** [comment]
CI breaks for Ruby 2.4

```
Cloning into 'dblock/ruby-enum'...
warning: Could not find remote branch ruby-240 to clone.
fatal: Remote branch ruby-240 not found in upstream origin
```

**Comment by laertispappas** [comment]
I forked a new branch from master (ruby-240) and pushed to origin. I will wait for CI to pass for Ruby 2.4

**Comment by laertispappas** [comment]
@dblock I need to ask you something currently I have 2 remotes:

* `origin` which points to my forked repo.
* `upstream` which points to your repo.

I made the release but rubygems fetched the project from my repo thus my forked origin/master is tagged with the new release. I should have change the origin to your remote correct? How do we fix this now?

**Comment by dblock** [comment]
When you make a release, do it from the non-forked repo. 

It's no big deal, I just did `git checkout 00c721da834570e9e3498620d8143dd6e4bcf901`, then `git tag v0.7.0` and `git push --tags`.

**Comment by dblock** [comment]
Thanks for doing the release @laertispappas!

**Comment by dblock** [comment]
You should continue working on your fork though for all code, except for doing the release.

**Comment by laertispappas** [comment]
@dblock great thanks for the explanation above.
