### ISSUE TITLE
5 Test failures on Alpine Linux

### ISSUE THREAD

**Issue by Ikke** [dblock/ruby-enum#21]
Ruby version: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-musl]
ruby-enum version: 0.7.2

While building ruby-enum for Alpine Linux, the suite reports the following errors:

> rspec ./spec/ruby-enum/enum_spec.rb:23 # Ruby::Enum raises UninitializedConstantError on an invalid constant
rspec ./spec/ruby-enum/enum_spec.rb:122 # Ruby::Enum on duplicate keys raises DuplicateKeyError
rspec ./spec/ruby-enum/enum_spec.rb:132 # Ruby::Enum on duplicate values raises a DuplicateValueError
rspec ./spec/ruby-enum/enum_spec.rb:145 # Ruby::Enum Given a class that has not defined any enums should raise Ruby::Enum::Errors::UninitializedConstantError
rspec ./spec/ruby-enum/enum_spec.rb:167 # Ruby::Enum Subclass behavior parent class should not have enums defined in child classes

See https://gist.github.com/Ikke/e9690849306977865e9df9f8598886a2 for the exceptions.

This might be due to the Ruby-i18n upgrade.

**Comment by dblock** [comment]
The error seems to be `LoadError: cannot load such file -- json`, are we accidentally bringing in a dependency on json somewhere?!

**Comment by Ikke** [comment]
Yes, that was the issue, adding the ruby json gem as dependencies made the tests run just fine.

Thanks!

**Comment by dblock** [comment]
Something that needs to be PRed here @Ikke ?

**Comment by Ikke** [comment]
I don't think this is an issue with rubu-enum, but with I18n.

This reproduces the error:

```ruby
require "i18n"
I18n::translate
```

Which results in:

> Traceback (most recent call last):
       12: from /usr/bin/irb:11:in \`\<main>'
       11: from (irb):4
       10: from /usr/lib/ruby/gems/2.5.0/gems/i18n-1.5.2/lib/i18n.rb:175:in \`translate'
        9: from /usr/lib/ruby/gems/2.5.0/gems/i18n-1.5.2/lib/i18n/config.rb:21:in \`backend'
        8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in \`require'
        7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in \`require'
        6: from /usr/lib/ruby/gems/2.5.0/gems/i18n-1.5.2/lib/i18n/backend/simple.rb:3:in \`<top (required)>'
        5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in \`require'
        4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in \`require'
        3: from /usr/lib/ruby/gems/2.5.0/gems/i18n-1.5.2/lib/i18n/backend/base.rb:4:in \`<top (required)>'
        2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in \`require'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in \`require'

**Comment by dblock** [comment]
Still, if you're maintaining a fork of ruby-enum I'd rather have that PRed into Gemfile here. It only affects tests so ...

**Comment by Ikke** [comment]
For the record, it's not a fork of ruby-enum. We are just [packaging][0] it. But we track dependencies in the alpine package metadata, and don't use bundle to install dependencies, so that's how the json dependency for i18n was missed.

So if you use bundler, it should automatically pick up json.

Hope this makes things clear.

Thank you for your quick response.

[0]:https://git.alpinelinux.org/aports/tree/community/ruby-enum/APKBUILD
