### ISSUE TITLE
Purpose of parse() method?

### ISSUE THREAD

**Issue by dmolesUC3** [dblock/ruby-enum#6]
From the documentation ("Attempts to parse an enumerated value"), I've been assuming the `parse()` method takes a value and returns the enum instance. I only discovered it didn't when I tried to use it with CONSTANT_CASE keys and CamelCase values:

```ruby
require 'ruby-enum'

class Example
  include Ruby::Enum

  define :FOO, 'Foo'
  define :BAR, 'Bar'
  define :BAZ_QUX, 'BazQux'
  define :CORGE_GRAUPLY, 'CorgeGrauply'
end

Example.values.each do |v|
  parsed = Example.parse(v)
  puts "#{v} : #{parsed}"
end

# => Foo : Foo
# => Bar : Bar
# => BazQux : 
# => CorgeGrauply : 
```

I've created two patches, one that clarifies the documentation, and another that adds a method `for_value()` that does what I thought `parse()` did, as well as a corresponding `for_key()`. See what you think.

**Comment by dblock** [comment]
Closed via https://github.com/dblock/ruby-enum/pull/8.
